// Generated by https://quicktype.io

export interface InfoDTO {
	type:    string;
	headers: Headers;
	payload: object;
}

export interface Headers {
	from:      string;
	to: string;
	hop_count: number;

}

