// Generated by https://quicktype.io

export interface MessageDTO {
	type:    string;
	headers: Headers;
	payload: string;
}

export interface Headers {
	from:      string;
	to:        string;
	hop_count: number;
}
